import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/providers/AuthProvider'
import { numericFont, primaryFont } from '@/lib/fonts'
import { ThemeProvider } from '@/providers/theme-provider'
import { Toaster } from 'sonner'
import Navbar from '@/components/home/nav/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <AuthProvider>
        <body
          className={` ${primaryFont.className} ${numericFont.className} adad min-h-screen`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <ModalProvider /> */}
            <Navbar />
            {children}

            <Toaster richColors position="bottom-left" />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  )
}
